# Generated by Django 5.2.3 on 2026-03-05 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('85', 'Vendee (85)'), ('56', 'Morbihan (56)'), ('44', 'Loire-Atlantique (44)'), ('35', 'Ille-et-Vilaine (35)')], max_length=2)),
                ('crop', models.CharField(choices=[('aubergine', 'Aubergine'), ('concombre', 'Concombre')], max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('week', models.PositiveSmallIntegerField()),
                ('aphid_infested_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('auxiliary_mode', models.CharField(choices=[('total', 'Abondance totale'), ('detailed', 'Detail par type')], default='total', max_length=10)),
                ('auxiliary_total', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-week', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuxiliaryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliary_type', models.CharField(choices=[('syrphe', 'Syrphe'), ('coccinelle', 'Coccinelle'), ('chrysope', 'Chrysope'), ('parasitoide', 'Parasitoide'), ('autre', 'Autre')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_counts', to='scouting.scoutingrecord')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('producer', 'Producteur'), ('technician', 'Technicien')], default='producer', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('85', 'Vendee (85)'), ('56', 'Morbihan (56)'), ('44', 'Loire-Atlantique (44)'), ('35', 'Ille-et-Vilaine (35)')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='scoutingrecord',
            constraint=models.UniqueConstraint(fields=('user', 'department', 'crop', 'year', 'week'), name='unique_record_per_user_crop_week'),
        ),
        migrations.AlterUniqueTogether(
            name='auxiliarycount',
            unique_together={('record', 'auxiliary_type')},
        ),
    ]
