# Generated by Django 5.2.3 on 2026-03-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crops_grown',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='farm_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tracked_plants',
            field=models.TextField(blank=True),
        ),
    ]
