# Generated by Django 5.2.3 on 2026-03-05 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0002_userprofile_crops_grown_userprofile_farm_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingrecord',
            name='scouting_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='LeafObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_number', models.PositiveSmallIntegerField()),
                ('leaf_position', models.CharField(choices=[('low', 'Basse'), ('mid', 'Milieu'), ('high', 'Haute')], max_length=5)),
                ('aphid_present', models.BooleanField(default=False)),
                ('syrphes', models.PositiveSmallIntegerField(default=0)),
                ('anthocorides', models.PositiveSmallIntegerField(default=0)),
                ('nabides', models.PositiveSmallIntegerField(default=0)),
                ('mirides', models.PositiveSmallIntegerField(default=0)),
                ('parasitoides', models.PositiveSmallIntegerField(default=0)),
                ('coccinelles', models.PositiveSmallIntegerField(default=0)),
                ('chrysopes_hemerobes', models.PositiveSmallIntegerField(default=0)),
                ('cecidiomyies', models.PositiveSmallIntegerField(default=0)),
                ('araignees', models.PositiveSmallIntegerField(default=0)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_observations', to='scouting.scoutingrecord')),
            ],
            options={
                'ordering': ['plant_number', 'leaf_position'],
                'constraints': [models.UniqueConstraint(fields=('record', 'plant_number', 'leaf_position'), name='unique_leaf_observation_per_record')],
            },
        ),
    ]
