# Generated by Django 5.2.3 on 2026-03-05 17:17

import django.db.models.deletion
from django.db import migrations, models


def seed_taxa_and_backfill(apps, schema_editor):
    AuxiliaryTaxon = apps.get_model('scouting', 'AuxiliaryTaxon')
    LeafObservation = apps.get_model('scouting', 'LeafObservation')
    LeafAuxiliaryObservation = apps.get_model('scouting', 'LeafAuxiliaryObservation')

    defaults = [
        ('syrphes', 'Syrphes'),
        ('anthocorides', 'Punaises Anthocorides'),
        ('nabides', 'Punaises Nabides'),
        ('mirides', 'Punaises Mirides'),
        ('parasitoides', 'Hymenopteres parasitoides adultes'),
        ('coccinelles', 'Coccinelles'),
        ('chrysopes_hemerobes', 'Chrysopes et Hemerobes'),
        ('cecidiomyies', 'Cecidomyies predatrices'),
        ('araignees', 'Araignees adultes'),
    ]
    taxa_by_code = {}
    for idx, (code, name) in enumerate(defaults, start=1):
        taxon, _ = AuxiliaryTaxon.objects.get_or_create(
            code=code,
            defaults={'name': name, 'display_order': idx, 'is_active': True},
        )
        taxa_by_code[code] = taxon

    rows = []
    for leaf in LeafObservation.objects.all().iterator():
        for code, _ in defaults:
            value = getattr(leaf, code, 0) or 0
            if value > 0:
                rows.append(
                    LeafAuxiliaryObservation(
                        leaf_observation_id=leaf.id,
                        taxon_id=taxa_by_code[code].id,
                        count=value,
                    )
                )
    if rows:
        LeafAuxiliaryObservation.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0003_scoutingrecord_scouting_date_leafobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryTaxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeafAuxiliaryObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('leaf_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_observations', to='scouting.leafobservation')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_counts', to='scouting.auxiliarytaxon')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('leaf_observation', 'taxon'), name='unique_aux_count_per_leaf_and_taxon')],
            },
        ),
        migrations.RunPython(seed_taxa_and_backfill, migrations.RunPython.noop),
    ]
