# Generated by Django 5.2.3 on 2026-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0004_auxiliarytaxon_leafauxiliaryobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliarytaxon',
            name='photo',
            field=models.ImageField(blank=True, upload_to='auxiliary_taxa/'),
        ),
    ]
