# Generated by Django 5.2.3 on 2026-03-11 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_leaf_index_and_seed_choices(apps, schema_editor):
    LeafObservation = apps.get_model('scouting', 'LeafObservation')
    Crop = apps.get_model('scouting', 'Crop')
    ConductType = apps.get_model('scouting', 'ConductType')
    Variety = apps.get_model('scouting', 'Variety')

    current_group = None
    idx = 0
    for leaf in LeafObservation.objects.all().order_by('record_id', 'plant_number', 'id').iterator():
        group = (leaf.record_id, leaf.plant_number)
        if group != current_group:
            current_group = group
            idx = 1
        else:
            idx += 1
        leaf.leaf_index = idx
        leaf.save(update_fields=['leaf_index'])

    aubergine, _ = Crop.objects.get_or_create(name='Aubergine', defaults={'is_active': True})
    concombre, _ = Crop.objects.get_or_create(name='Concombre', defaults={'is_active': True})
    ConductType.objects.get_or_create(name='Sous abri', defaults={'is_active': True})
    if any(field.name == 'crop' for field in Variety._meta.fields):
        Variety.objects.get_or_create(crop=aubergine, name='Standard', defaults={'is_active': True})
        Variety.objects.get_or_create(crop=concombre, name='Standard', defaults={'is_active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0005_auxiliarytaxon_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('plants_count', models.PositiveSmallIntegerField(default=10)),
                ('leaves_per_plant', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='leafobservation',
            options={'ordering': ['plant_number', 'leaf_index']},
        ),
        migrations.RemoveConstraint(
            model_name='leafobservation',
            name='unique_leaf_observation_per_record',
        ),
        migrations.RemoveConstraint(
            model_name='scoutingrecord',
            name='unique_record_per_user_crop_week',
        ),
        migrations.AddField(
            model_name='leafobservation',
            name='leaf_index',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='leaf_position',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='crop',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='scoutingrecord',
            name='conduct_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='scouting.conducttype'),
        ),
        migrations.AddField(
            model_name='scoutingrecord',
            name='crop_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='scouting.crop'),
        ),
        migrations.AddField(
            model_name='plantseries',
            name='conduct_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_series', to='scouting.conducttype'),
        ),
        migrations.AddField(
            model_name='plantseries',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_series', to='scouting.crop'),
        ),
        migrations.AddField(
            model_name='plantseries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutingrecord',
            name='plant_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='scouting.plantseries'),
        ),
        migrations.AddField(
            model_name='variety',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_varieties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variety',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='scouting.crop'),
        ),
        migrations.AddField(
            model_name='plantseries',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_series', to='scouting.variety'),
        ),
        migrations.AddField(
            model_name='scoutingrecord',
            name='variety_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='scouting.variety'),
        ),
        migrations.RunPython(backfill_leaf_index_and_seed_choices, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='leafobservation',
            constraint=models.UniqueConstraint(fields=('record', 'plant_number', 'leaf_index'), name='unique_leaf_observation_per_record'),
        ),
        migrations.AddConstraint(
            model_name='scoutingrecord',
            constraint=models.UniqueConstraint(fields=('user', 'plant_series', 'year', 'week'), name='unique_record_per_user_crop_week'),
        ),
        migrations.AddConstraint(
            model_name='variety',
            constraint=models.UniqueConstraint(fields=('crop', 'name'), name='unique_variety_per_crop'),
        ),
        migrations.AddConstraint(
            model_name='plantseries',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_series_name_per_user'),
        ),
    ]
