# Generated by Django 5.2.3 on 2026-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0006_conducttype_crop_plantseries_variety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantseries',
            name='photo',
            field=models.ImageField(blank=True, upload_to='plant_series/'),
        ),
    ]
