# Generated by Django 5.2.3 on 2026-03-16 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_action_types(apps, schema_editor):
    ActionType = apps.get_model('scouting', 'ActionType')
    defaults = [
        ('Action manuelle', 'manual', 1),
        ('Traitement', 'treatment', 2),
        ("Lacher d'auxiliaires", 'release', 3),
    ]
    for name, category, display_order in defaults:
        ActionType.objects.update_or_create(
            name=name,
            defaults={
                'category': category,
                'display_order': display_order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0007_plantseries_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('manual', 'Manuelle'), ('treatment', 'Traitement'), ('release', "Lacher d'auxiliaire")], default='manual', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='auxiliarytaxon',
            name='is_releasable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantseries',
            name='organic_mode',
            field=models.CharField(choices=[('bio', 'Bio (AB)'), ('non_bio', 'Non bio')], default='bio', max_length=10),
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('organic_scope', models.CharField(choices=[('bio', 'Bio (AB)'), ('non_bio', 'Non bio'), ('both', 'Bio et non bio')], default='both', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecules', to='scouting.crop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('85', 'Vendee (85)'), ('56', 'Morbihan (56)'), ('44', 'Loire-Atlantique (44)'), ('35', 'Ille-et-Vilaine (35)')], max_length=2)),
                ('action_date', models.DateField(default=django.utils.timezone.localdate)),
                ('scope', models.CharField(choices=[('localized', 'Localisee'), ('general', 'Generalisee')], default='general', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.actiontype')),
                ('auxiliary_taxon', models.ForeignKey(blank=True, limit_choices_to={'is_releasable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_actions', to='scouting.auxiliarytaxon')),
                ('conduct_type_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.conducttype')),
                ('crop_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.crop')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_plant_actions', to=settings.AUTH_USER_MODEL)),
                ('molecule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.molecule')),
                ('plant_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.plantseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_actions', to=settings.AUTH_USER_MODEL)),
                ('variety_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.variety')),
            ],
            options={
                'ordering': ['-action_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='molecule',
            constraint=models.UniqueConstraint(fields=('name', 'crop', 'organic_scope'), name='unique_molecule_per_crop_scope'),
        ),
        migrations.RunPython(seed_action_types, migrations.RunPython.noop),
    ]
