# Generated by Django 5.2.3 on 2026-03-16 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_street_address(apps, schema_editor):
    UserProfile = apps.get_model('scouting', 'UserProfile')
    for profile in UserProfile.objects.exclude(farm_address='').filter(street_address=''):
        profile.street_address = profile.farm_address[:255]
        profile.save(update_fields=['street_address'])


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0008_actiontype_auxiliarytaxon_is_releasable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_producer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_street_address, migrations.RunPython.noop),
    ]
