# Generated by Django 5.2.3 on 2026-03-16 15:28

from django.db import migrations, models


def migrate_molecule_crops(apps, schema_editor):
    Molecule = apps.get_model('scouting', 'Molecule')
    PlantAction = apps.get_model('scouting', 'PlantAction')
    MoleculeCrop = Molecule.crops.through

    seen_links = set()
    molecules = list(Molecule.objects.all().order_by('id'))
    grouped = {}

    for molecule in molecules:
        key = (molecule.name, molecule.organic_scope)
        grouped.setdefault(key, []).append(molecule)
        if molecule.crop_id:
            link = (molecule.id, molecule.crop_id)
            if link not in seen_links:
                MoleculeCrop.objects.get_or_create(molecule_id=molecule.id, crop_id=molecule.crop_id)
                seen_links.add(link)

    for (_name, _scope), rows in grouped.items():
        if len(rows) <= 1:
            continue
        keeper = rows[0]
        duplicate_ids = [row.id for row in rows[1:]]
        crop_ids = set(
            MoleculeCrop.objects.filter(molecule_id__in=[row.id for row in rows]).values_list('crop_id', flat=True)
        )
        for crop_id in crop_ids:
            MoleculeCrop.objects.get_or_create(molecule_id=keeper.id, crop_id=crop_id)
        PlantAction.objects.filter(molecule_id__in=duplicate_ids).update(molecule_id=keeper.id)
        Molecule.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0009_userprofile_assigned_technician_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='crops',
            field=models.ManyToManyField(blank=True, related_name='molecules', to='scouting.crop'),
        ),
        migrations.RunPython(migrate_molecule_crops, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='molecule',
            name='unique_molecule_per_crop_scope',
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='crop',
        ),
        migrations.AddConstraint(
            model_name='molecule',
            constraint=models.UniqueConstraint(fields=('name', 'organic_scope'), name='unique_molecule_per_scope'),
        ),
    ]
