# Generated by Django 5.2.3 on 2026-03-16 16:44

import django.db.models.deletion
import django.utils.timezone
import scouting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0010_remove_molecule_unique_molecule_per_crop_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description du levier')),
                ('scope', models.CharField(choices=[('localized', 'Localisee'), ('general', 'Generalisee')], default='general', max_length=12, verbose_name='Portee')),
                ('notes_template', models.TextField(blank=True, verbose_name='Details preraplis')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Levier de decision',
                'verbose_name_plural': 'Leviers de decision',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DecisionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('week_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semaine min incluse')),
                ('week_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semaine max incluse')),
                ('infestation_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Infestation min incluse (%)')),
                ('infestation_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Infestation max exclue (%)')),
                ('auxiliary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Auxiliaires min inclus')),
                ('auxiliary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Auxiliaires max exclu')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='Priorite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creee le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise a jour le')),
            ],
            options={
                'verbose_name': 'Regle de decision',
                'verbose_name_plural': 'Regles de decision',
                'ordering': ['crop__name', 'priority', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='actiontype',
            options={'ordering': ['display_order', 'name'], 'verbose_name': "Type d'action", 'verbose_name_plural': "Types d'action"},
        ),
        migrations.AlterModelOptions(
            name='auxiliarycount',
            options={'verbose_name': "Compte d'auxiliaire", 'verbose_name_plural': "Comptes d'auxiliaires"},
        ),
        migrations.AlterModelOptions(
            name='auxiliarytaxon',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Auxiliaire', 'verbose_name_plural': 'Auxiliaires'},
        ),
        migrations.AlterModelOptions(
            name='conducttype',
            options={'ordering': ['name'], 'verbose_name': 'Type de conduite', 'verbose_name_plural': 'Types de conduite'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name'], 'verbose_name': 'Culture', 'verbose_name_plural': 'Cultures'},
        ),
        migrations.AlterModelOptions(
            name='leafauxiliaryobservation',
            options={'verbose_name': "Observation d'auxiliaire", 'verbose_name_plural': "Observations d'auxiliaires"},
        ),
        migrations.AlterModelOptions(
            name='leafobservation',
            options={'ordering': ['plant_number', 'leaf_index'], 'verbose_name': 'Observation de feuille', 'verbose_name_plural': 'Observations de feuilles'},
        ),
        migrations.AlterModelOptions(
            name='molecule',
            options={'ordering': ['name'], 'verbose_name': 'Molecule', 'verbose_name_plural': 'Molecules'},
        ),
        migrations.AlterModelOptions(
            name='plantaction',
            options={'ordering': ['-action_date', '-created_at'], 'verbose_name': 'Action preventive ou curative', 'verbose_name_plural': 'Actions preventives ou curatives'},
        ),
        migrations.AlterModelOptions(
            name='plantseries',
            options={'ordering': ['name'], 'verbose_name': 'Serie de plants', 'verbose_name_plural': 'Series de plants'},
        ),
        migrations.AlterModelOptions(
            name='scoutingrecord',
            options={'ordering': ['-year', '-week', '-created_at'], 'verbose_name': 'Comptage', 'verbose_name_plural': 'Comptages'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'ordering': ['name'], 'verbose_name': 'Variete', 'verbose_name_plural': 'Varietes'},
        ),
        migrations.RemoveConstraint(
            model_name='plantseries',
            name='unique_series_name_per_user',
        ),
        migrations.AddField(
            model_name='crop',
            name='decision_aux_metric',
            field=models.CharField(choices=[('per_plant', 'Auxiliaires / plant'), ('per_observed_leaf', 'Auxiliaires / feuille observee'), ('per_infested_leaf', 'Auxiliaires / feuille infestee')], default='per_plant', max_length=30, verbose_name='Indicateur auxiliaires pour la decision'),
        ),
        migrations.AddField(
            model_name='plantseries',
            name='year',
            field=models.PositiveSmallIntegerField(default=scouting.models.current_campaign_year, verbose_name='Annee'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='category',
            field=models.CharField(choices=[('manual', 'Manuelle'), ('treatment', 'Traitement'), ('release', "Lacher d'auxiliaire")], default='manual', max_length=20, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='auxiliarycount',
            name='auxiliary_type',
            field=models.CharField(choices=[('syrphe', 'Syrphe'), ('coccinelle', 'Coccinelle'), ('chrysope', 'Chrysope'), ('parasitoide', 'Parasitoide'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'auxiliaire"),
        ),
        migrations.AlterField(
            model_name='auxiliarycount',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='auxiliarycount',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_counts', to='scouting.scoutingrecord', verbose_name='Comptage'),
        ),
        migrations.AlterField(
            model_name='auxiliarytaxon',
            name='code',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='auxiliarytaxon',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='auxiliarytaxon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='auxiliarytaxon',
            name='is_releasable',
            field=models.BooleanField(default=False, verbose_name='Lachable'),
        ),
        migrations.AlterField(
            model_name='auxiliarytaxon',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='auxiliarytaxon',
            name='photo',
            field=models.ImageField(blank=True, upload_to='auxiliary_taxa/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='conducttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='conducttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='leafauxiliaryobservation',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='leafauxiliaryobservation',
            name='leaf_observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_observations', to='scouting.leafobservation', verbose_name='Observation de feuille'),
        ),
        migrations.AlterField(
            model_name='leafauxiliaryobservation',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_counts', to='scouting.auxiliarytaxon', verbose_name='Auxiliaire'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='anthocorides',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Punaises Anthocorides'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='aphid_present',
            field=models.BooleanField(default=False, verbose_name='Puceron present'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='araignees',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Araignees adultes'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='cecidiomyies',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cecidomyies predatrices'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='chrysopes_hemerobes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Chrysopes et Hemerobes'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='coccinelles',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Coccinelles'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='leaf_index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Index de feuille'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='leaf_position',
            field=models.CharField(max_length=30, verbose_name='Position de la feuille'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='mirides',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Punaises Mirides'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='nabides',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Punaises Nabides'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='parasitoides',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Hymenopteres parasitoides adultes'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='plant_number',
            field=models.PositiveSmallIntegerField(verbose_name='Numero du plant'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_observations', to='scouting.scoutingrecord', verbose_name='Comptage'),
        ),
        migrations.AlterField(
            model_name='leafobservation',
            name='syrphes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Syrphes'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='crops',
            field=models.ManyToManyField(blank=True, related_name='molecules', to='scouting.crop', verbose_name='Cultures'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='organic_scope',
            field=models.CharField(choices=[('bio', 'Bio (AB)'), ('non_bio', 'Non bio'), ('both', 'Bio et non bio')], default='both', max_length=10, verbose_name='Portee bio/non bio'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='action_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="Date d'action"),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.actiontype', verbose_name="Type d'action"),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='auxiliary_taxon',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_releasable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_actions', to='scouting.auxiliarytaxon', verbose_name='Auxiliaire lache'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='conduct_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.conducttype', verbose_name='Conduite'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creee le'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='crop_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.crop', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='department',
            field=models.CharField(choices=[('85', 'Vendee (85)'), ('56', 'Morbihan (56)'), ('44', 'Loire-Atlantique (44)'), ('35', 'Ille-et-Vilaine (35)')], max_length=2, verbose_name='Departement'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_plant_actions', to=settings.AUTH_USER_MODEL, verbose_name='Saisie par'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='molecule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.molecule', verbose_name='Molecule'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='plant_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.plantseries', verbose_name='Serie de plants'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='scope',
            field=models.CharField(choices=[('localized', 'Localisee'), ('general', 'Generalisee')], default='general', max_length=12, verbose_name='Portee'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_actions', to=settings.AUTH_USER_MODEL, verbose_name='Producteur'),
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='variety_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='scouting.variety', verbose_name='Variete'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='conduct_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_series', to='scouting.conducttype', verbose_name='Conduite'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creee le'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_series', to='scouting.crop', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='leaves_per_plant',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Nombre de feuilles par plant'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom de la serie'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='organic_mode',
            field=models.CharField(choices=[('bio', 'Bio (AB)'), ('non_bio', 'Non bio')], default='bio', max_length=10, verbose_name='Mode de conduite'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='photo',
            field=models.ImageField(blank=True, upload_to='plant_series/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='plants_count',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Nombre de plants'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_series', to=settings.AUTH_USER_MODEL, verbose_name='Producteur'),
        ),
        migrations.AlterField(
            model_name='plantseries',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_series', to='scouting.variety', verbose_name='Variete'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='aphid_infested_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% feuilles infestees'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='auxiliary_mode',
            field=models.CharField(choices=[('total', 'Abondance totale'), ('detailed', 'Detail par type')], default='total', max_length=10, verbose_name='Mode auxiliaires'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='auxiliary_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total auxiliaires'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='conduct_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='scouting.conducttype', verbose_name='Conduite'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='crop',
            field=models.CharField(max_length=100, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='crop_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='scouting.crop', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='department',
            field=models.CharField(choices=[('85', 'Vendee (85)'), ('56', 'Morbihan (56)'), ('44', 'Loire-Atlantique (44)'), ('35', 'Ille-et-Vilaine (35)')], max_length=2, verbose_name='Departement'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='plant_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='scouting.plantseries', verbose_name='Serie de plants'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='scouting_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date observation'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='Producteur'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='variety_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='scouting.variety', verbose_name='Variete'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='week',
            field=models.PositiveSmallIntegerField(verbose_name='Semaine'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Annee'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_producer_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Technicien referent'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='crops_grown',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cultures suivies'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('85', 'Vendee (85)'), ('56', 'Morbihan (56)'), ('44', 'Loire-Atlantique (44)'), ('35', 'Ille-et-Vilaine (35)')], max_length=2, verbose_name='Departement'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='farm_address',
            field=models.TextField(blank=True, verbose_name='Adresse complete'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom de ferme'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('producer', 'Producteur'), ('technician', 'Technicien')], default='producer', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tracked_plants',
            field=models.TextField(blank=True, verbose_name='Plants suivis'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_varieties', to=settings.AUTH_USER_MODEL, verbose_name='Creee par'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='scouting.crop', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AddConstraint(
            model_name='plantseries',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'name'), name='unique_series_name_per_user_year'),
        ),
        migrations.AddField(
            model_name='decisionlever',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_levers', to='scouting.actiontype', verbose_name="Type d'action"),
        ),
        migrations.AddField(
            model_name='decisionlever',
            name='auxiliary_taxon',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_releasable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_levers', to='scouting.auxiliarytaxon', verbose_name='Auxiliaire preselectionne'),
        ),
        migrations.AddField(
            model_name='decisionlever',
            name='molecule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_levers', to='scouting.molecule', verbose_name='Molecule preselectionnee'),
        ),
        migrations.AddField(
            model_name='plantaction',
            name='decision_lever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='scouting.decisionlever', verbose_name='Levier active'),
        ),
        migrations.AddField(
            model_name='decisionrule',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_rules', to='scouting.crop', verbose_name='Culture'),
        ),
        migrations.AddField(
            model_name='decisionlever',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levers', to='scouting.decisionrule', verbose_name='Regle'),
        ),
    ]
