# Generated by Django 5.2.3 on 2026-03-20 12:09

import django.db.models.deletion
from django.db import migrations, models


def create_default_info_pages(apps, schema_editor):
    InfoPage = apps.get_model('scouting', 'InfoPage')
    defaults = [
        ('protocol', 'Protocole'),
        ('techniques', 'Techniques de lutte'),
        ('auxiliaries', 'Auxiliaires'),
    ]
    for page_key, title in defaults:
        InfoPage.objects.get_or_create(
            page_key=page_key,
            defaults={
                'title': title,
                'intro': 'Contenu a completer dans l admin.',
                'content': '',
                'is_published': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0011_decisionlever_decisionrule_alter_actiontype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('protocol', 'Protocole'), ('techniques', 'Techniques de lutte'), ('auxiliaries', 'Auxiliaires')], max_length=30, unique=True, verbose_name='Page')),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('intro', models.TextField(blank=True, verbose_name='Introduction')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiee')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise a jour le')),
            ],
            options={
                'verbose_name': "Page d'information",
                'verbose_name_plural': "Pages d'information",
                'ordering': ['page_key'],
            },
        ),
        migrations.CreateModel(
            name='InfoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, upload_to='info_resources/', verbose_name='Fichier')),
                ('external_url', models.URLField(blank=True, verbose_name='Lien externe')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='scouting.infopage', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.RunPython(create_default_info_pages, migrations.RunPython.noop),
    ]
