# Generated by Django 5.2.3 on 2026-03-20 15:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0012_infopage_inforesource'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_key', models.CharField(blank=True, choices=[('protocol', 'Protocole'), ('techniques', 'Techniques de lutte'), ('auxiliaries', 'Auxiliaires')], max_length=30, null=True, unique=True, verbose_name='Code de page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu')),
            ],
            options={
                'verbose_name': "Page d'information CMS",
                'verbose_name_plural': "Pages d'information CMS",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InfoIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
            ],
            options={
                'verbose_name': "Index des pages d'information",
                'verbose_name_plural': "Index des pages d'information",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InfoContentPageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('external_url', models.URLField(blank=True, verbose_name='Lien externe')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='scouting.infocontentpage', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Ressource CMS',
                'verbose_name_plural': 'Ressources CMS',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
