# Generated by Django 5.2.3 on 2026-03-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_dismiss_reasons(apps, schema_editor):
    RecommendationDismissReason = apps.get_model('scouting', 'RecommendationDismissReason')
    defaults = [
        ("Plus besoin d'agir", False, 1),
        ('Pas envie de mobiliser ce levier', False, 2),
        ('Autre', True, 3),
    ]
    for label, requires_comment, display_order in defaults:
        RecommendationDismissReason.objects.get_or_create(
            label=label,
            defaults={
                'requires_comment': requires_comment,
                'display_order': display_order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0014_migrate_info_pages_to_wagtail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationDismissReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160, unique=True, verbose_name='Libelle')),
                ('requires_comment', models.BooleanField(default=False, verbose_name='Texte libre propose')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Motif de non-suivi',
                'verbose_name_plural': 'Motifs de non-suivi',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('followed', 'Suivie'), ('dismissed', 'Non suivie')], max_length=12, verbose_name='Statut')),
                ('dismiss_note', models.TextField(blank=True, verbose_name='Precision libre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creee le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise a jour le')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_responses', to='scouting.plantaction', verbose_name='Action creee')),
                ('dismiss_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='scouting.recommendationdismissreason', verbose_name='Motif de non-suivi')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_recommendation_responses', to=settings.AUTH_USER_MODEL, verbose_name='Traitee par')),
                ('lever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='scouting.decisionlever', verbose_name='Levier suivi')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_responses', to='scouting.scoutingrecord', verbose_name='Comptage')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='scouting.decisionrule', verbose_name='Regle de decision')),
            ],
            options={
                'verbose_name': 'Traitement de recommandation',
                'verbose_name_plural': 'Traitements de recommandation',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('record', 'rule'), name='unique_recommendation_response_per_record_rule')],
            },
        ),
        migrations.RunPython(create_default_dismiss_reasons, migrations.RunPython.noop),
    ]
