# Generated by Django 5.2.3 on 2026-03-20 15:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0015_recommendationdismissreason_recommendationresponse'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funders_title', models.CharField(default='Financeurs', max_length=160, verbose_name='Titre financeurs')),
                ('funders_text', wagtail.fields.RichTextField(blank=True, verbose_name='Texte financeurs')),
                ('funders_logos', wagtail.fields.StreamField([('logo', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Logo', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Texte alternatif', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Lien', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt', 1), ('url', 2)]], {})}, verbose_name='Logos financeurs')),
                ('footer_title', models.CharField(default='Bas de page', max_length=160, verbose_name='Titre footer')),
                ('footer_text', wagtail.fields.RichTextField(blank=True, verbose_name='Texte footer')),
                ('footer_logos', wagtail.fields.StreamField([('logo', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Logo', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Texte alternatif', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Lien', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt', 1), ('url', 2)]], {})}, verbose_name='Logos footer')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Contenus globaux du site',
                'verbose_name_plural': 'Contenus globaux du site',
            },
        ),
    ]
