# Generated by Django 5.2.3 on 2026-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0017_userprofile_phone_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='chart_icon',
            field=models.CharField(blank=True, choices=[('triangle', 'Triangle'), ('circle', 'Cercle'), ('rectRot', 'Losange'), ('rectRounded', 'Rectangle'), ('star', 'Etoile'), ('crossRot', 'Croix')], max_length=20, verbose_name='Icone graphique'),
        ),
    ]
