# Generated by Django 5.2.3 on 2026-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0018_actiontype_chart_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mobile'),
        ),
    ]
