# Generated by Django 5.2.3 on 2026-04-03 10:54

import django.db.models.deletion
from django.db import migrations, models


def seed_aphid_species(apps, schema_editor):
    AphidSpecies = apps.get_model('scouting', 'AphidSpecies')
    species_rows = [
        ('non-determine', 'Non determine', '', 1),
        ('macrosiphum-euphorbiae', 'Macrosiphum euphorbiae', '', 2),
        ('myzus-persicae', 'Myzus persicae', '', 3),
        ('aphis-gossypii', 'Aphis gossypii', '', 4),
        ('aphis-fabae', 'Aphis fabae', '', 5),
        ('aulacorthum-solani', 'Aulacorthum solani', '', 6),
        ('autre', 'Autre', '', 7),
    ]
    for code, vernacular_name, latin_name, display_order in species_rows:
        AphidSpecies.objects.update_or_create(
            code=code,
            defaults={
                'vernacular_name': vernacular_name,
                'latin_name': latin_name,
                'display_order': display_order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0019_alter_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AphidSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('vernacular_name', models.CharField(max_length=140, verbose_name='Nom vernaculaire')),
                ('latin_name', models.CharField(blank=True, max_length=140, verbose_name='Nom latin')),
                ('photo', models.ImageField(blank=True, upload_to='aphid_species/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('auxiliary_taxa', models.ManyToManyField(blank=True, related_name='target_aphid_species', to='scouting.auxiliarytaxon', verbose_name='Auxiliaires de lutte')),
                ('molecules', models.ManyToManyField(blank=True, related_name='aphid_species', to='scouting.molecule', verbose_name='Molecules de lutte')),
            ],
            options={
                'verbose_name': 'Espece de puceron',
                'verbose_name_plural': 'Especes de pucerons',
                'ordering': ['display_order', 'vernacular_name', 'latin_name'],
            },
        ),
        migrations.RunPython(seed_aphid_species, migrations.RunPython.noop),
        migrations.AddField(
            model_name='leafobservation',
            name='aphid_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_observations', to='scouting.aphidspecies', verbose_name='Espece de puceron'),
        ),
        migrations.AddField(
            model_name='scoutingrecord',
            name='primary_aphid_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_records', to='scouting.aphidspecies', verbose_name='Espece principale de puceron'),
        ),
    ]
