# Generated by Django 5.2.3 on 2026-04-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0020_aphidspecies_leafobservation_aphid_species_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontentsettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Icône du site affichée dans l’onglet du navigateur et sur l’écran d’accueil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon'),
        ),
    ]
