# Generated by Django 5.2.3 on 2026-04-07 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0021_sitecontentsettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantseries',
            name='planting_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)], verbose_name='Numero de la semaine de plantation'),
        ),
    ]
