# Generated by Django 5.2.3 on 2026-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0022_plantseries_planting_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantseries',
            name='greenhouse',
            field=models.CharField(blank=True, max_length=150, verbose_name='Serre'),
        ),
    ]
