# Generated by Codex on 2026-04-08

from django.db import migrations


def normalize_user_emails(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    seen = {}
    for user in User.objects.all().order_by('id'):
        cleaned = (user.email or '').strip().lower()
        if user.email != cleaned:
            user.email = cleaned
            user.save(update_fields=['email'])
        if cleaned:
            if cleaned in seen:
                raise RuntimeError(
                    f"Adresse mail dupliquee avant migration: {cleaned} (utilisateurs {seen[cleaned]} et {user.id})."
                )
            seen[cleaned] = user.id


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('scouting', '0023_plantseries_greenhouse'),
    ]

    operations = [
        migrations.RunPython(normalize_user_emails, migrations.RunPython.noop),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX IF NOT EXISTS auth_user_email_ci_unique_nonblank "
                "ON auth_user (LOWER(email)) "
                "WHERE email IS NOT NULL AND email <> '';"
            ),
            reverse_sql="DROP INDEX IF EXISTS auth_user_email_ci_unique_nonblank;",
        ),
    ]
