# Generated by Django 5.2.3 on 2026-04-08 15:02

import django.db.models.deletion
from django.db import migrations, models


def seed_other_pest_taxa(apps, schema_editor):
    OtherPestTaxon = apps.get_model('scouting', 'OtherPestTaxon')
    seeds = [
        ('acariens', 'Acariens', 1),
        ('aleurodes', 'Aleurodes', 2),
        ('punaises-phytophages', 'Punaises phytophages', 3),
        ('thrips', 'Thrips', 4),
        ('tuta-absoluta', 'Tuta absoluta', 5),
        ('autres-chenilles', 'Autres chenilles', 6),
    ]
    for code, name, display_order in seeds:
        OtherPestTaxon.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'display_order': display_order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0024_auth_user_email_unique_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPestTaxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=140, verbose_name='Nom')),
                ('photo', models.ImageField(blank=True, upload_to='other_pest_taxa/', verbose_name='Photo')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Autre ravageur',
                'verbose_name_plural': 'Autres ravageurs',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeafOtherPestObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_pest_observations', to='scouting.leafobservation', verbose_name='Observation de feuille')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_observations', to='scouting.otherpesttaxon', verbose_name='Autre ravageur')),
            ],
            options={
                'verbose_name': "Observation d'autre ravageur",
                'verbose_name_plural': "Observations d'autres ravageurs",
                'constraints': [models.UniqueConstraint(fields=('leaf_observation', 'taxon'), name='unique_other_pest_per_leaf_and_taxon')],
            },
        ),
        migrations.RunPython(seed_other_pest_taxa, migrations.RunPython.noop),
    ]
