# Generated by Django 5.2.3 on 2026-04-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0025_otherpesttaxon_leafotherpestobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingrecord',
            name='aphid_infested_leaves_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Feuilles infestees de pucerons'),
        ),
        migrations.AddField(
            model_name='scoutingrecord',
            name='entry_mode',
            field=models.CharField(choices=[('detailed', 'Comptage detaille'), ('quick', 'Comptage rapide')], default='detailed', max_length=10, verbose_name='Mode de saisie'),
        ),
        migrations.AddField(
            model_name='scoutingrecord',
            name='observed_leaves_count',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Feuilles observees'),
        ),
        migrations.AddField(
            model_name='scoutingrecord',
            name='observed_plants_count',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Plants observes'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='auxiliary_mode',
            field=models.CharField(choices=[('total', 'Abondance totale'), ('detailed', 'Detail par type'), ('quick', 'Saisie rapide')], default='total', max_length=10, verbose_name='Mode auxiliaires'),
        ),
        migrations.CreateModel(
            name='QuickRecordAphidSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_aphid_species', to='scouting.scoutingrecord', verbose_name='Comptage')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_records', to='scouting.aphidspecies', verbose_name='Espece de puceron')),
            ],
            options={
                'verbose_name': 'Espece de puceron observee (rapide)',
                'verbose_name_plural': 'Especes de pucerons observees (rapide)',
                'constraints': [models.UniqueConstraint(fields=('record', 'species'), name='unique_quick_aphid_species_per_record')],
            },
        ),
        migrations.CreateModel(
            name='QuickRecordAuxiliaryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_auxiliary_counts', to='scouting.scoutingrecord', verbose_name='Comptage')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_record_counts', to='scouting.auxiliarytaxon', verbose_name='Auxiliaire')),
            ],
            options={
                'verbose_name': "Compte d'auxiliaire (rapide)",
                'verbose_name_plural': "Comptes d'auxiliaires (rapide)",
                'constraints': [models.UniqueConstraint(fields=('record', 'taxon'), name='unique_quick_aux_count_per_record_and_taxon')],
            },
        ),
        migrations.CreateModel(
            name='QuickRecordOtherPestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infested_leaves_count', models.PositiveSmallIntegerField(default=0, verbose_name='Feuilles infestees')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_other_pest_counts', to='scouting.scoutingrecord', verbose_name='Comptage')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_record_counts', to='scouting.otherpesttaxon', verbose_name='Autre ravageur')),
            ],
            options={
                'verbose_name': "Observation d'autre ravageur (rapide)",
                'verbose_name_plural': "Observations d'autres ravageurs (rapide)",
                'constraints': [models.UniqueConstraint(fields=('record', 'taxon'), name='unique_quick_pest_count_per_record_and_taxon')],
            },
        ),
    ]
