# Generated by Django 5.2.3 on 2026-04-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0026_scoutingrecord_aphid_infested_leaves_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=140, verbose_name='Nom')),
                ('latin_name', models.CharField(blank=True, max_length=140, verbose_name='Nom latin')),
                ('photo', models.ImageField(blank=True, upload_to='service_plants/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Plante de service',
                'verbose_name_plural': 'Plantes de service',
                'ordering': ['display_order', 'name', 'latin_name'],
            },
        ),
        migrations.AddField(
            model_name='plantseries',
            name='has_service_plants',
            field=models.BooleanField(default=False, verbose_name='Presence de plantes de service'),
        ),
        migrations.AddField(
            model_name='plantseries',
            name='service_plants',
            field=models.ManyToManyField(blank=True, related_name='plant_series', to='scouting.serviceplant', verbose_name='Plantes de service'),
        ),
    ]
