# Generated by Django 5.2.3 on 2026-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0028_load_default_service_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontentsettings',
            name='footer_title',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Titre footer'),
        ),
    ]
