# Generated by Django 5.2.3 on 2026-04-10 13:54

from django.db import migrations, models


def seed_departments(apps, schema_editor):
    Department = apps.get_model('scouting', 'Department')
    UserProfile = apps.get_model('scouting', 'UserProfile')
    ScoutingRecord = apps.get_model('scouting', 'ScoutingRecord')
    PlantAction = apps.get_model('scouting', 'PlantAction')

    default_departments = {
        '35': 'Ille-et-Vilaine',
        '44': 'Loire-Atlantique',
        '56': 'Morbihan',
        '85': 'Vendee',
    }

    for code, name in default_departments.items():
        Department.objects.get_or_create(code=code, defaults={'name': name, 'is_active': True})

    existing_codes = set()
    existing_codes.update(UserProfile.objects.exclude(department='').values_list('department', flat=True))
    existing_codes.update(ScoutingRecord.objects.exclude(department='').values_list('department', flat=True))
    existing_codes.update(PlantAction.objects.exclude(department='').values_list('department', flat=True))

    for raw_code in existing_codes:
        code = (raw_code or '').strip()
        if not code:
            continue
        Department.objects.get_or_create(
            code=code,
            defaults={'name': default_departments.get(code, f'Departement {code}'), 'is_active': True},
        )


def unseed_departments(apps, schema_editor):
    # Keep data on rollback to avoid deleting manually created departments.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0029_alter_sitecontentsettings_footer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='plantaction',
            name='department',
            field=models.CharField(max_length=10, verbose_name='Departement'),
        ),
        migrations.AlterField(
            model_name='scoutingrecord',
            name='department',
            field=models.CharField(max_length=10, verbose_name='Departement'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=10, verbose_name='Departement'),
        ),
        migrations.RunPython(seed_departments, unseed_departments),
    ]
