# Generated by Django 5.2.3 on 2026-04-22 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def bootstrap_access_control_settings(apps, schema_editor):
    AccessControlSettings = apps.get_model('scouting', 'AccessControlSettings')
    if not AccessControlSettings.objects.exists():
        AccessControlSettings.objects.create()


def unbootstrap_access_control_settings(apps, schema_editor):
    # Keep configured settings on rollback.
    pass


def backfill_legacy_technician_assignments(apps, schema_editor):
    UserProfile = apps.get_model('scouting', 'UserProfile')
    ProducerTechnicianAssignment = apps.get_model('scouting', 'ProducerTechnicianAssignment')

    producer_profiles = UserProfile.objects.filter(role='producer').exclude(assigned_technician_id__isnull=True)
    for profile in producer_profiles.iterator():
        ProducerTechnicianAssignment.objects.get_or_create(
            producer_profile_id=profile.id,
            technician_id=profile.assigned_technician_id,
            is_active=True,
        )


def unbackfill_legacy_technician_assignments(apps, schema_editor):
    # Keep migrated assignments on rollback to avoid data loss.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0030_department_alter_plantaction_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_producer_readonly_message', models.TextField(blank=True, default="Votre compte est actuellement en lecture seule car aucun technicien actif n'est rattache a votre profil.", verbose_name='Message global lecture seule producteur')),
                ('default_technician_denied_message', models.TextField(blank=True, default='Votre licence technicien est inactive. Contactez le super-admin.', verbose_name='Message global acces refuse technicien')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
            ],
            options={
                'verbose_name': "Parametres d'acces",
                'verbose_name_plural': "Parametres d'acces",
            },
        ),
        migrations.CreateModel(
            name='TechnicianStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Structure')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('logo', models.ImageField(blank=True, upload_to='technician_structures/', verbose_name='Logo')),
                ('generic_contact', models.CharField(blank=True, max_length=160, verbose_name='Contact generic')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
            ],
            options={
                'verbose_name': 'Structure technicien',
                'verbose_name_plural': 'Structures technicien',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivation_message',
            field=models.TextField(blank=True, verbose_name='Message desactivation / arret de suivi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspendue')], default='active', max_length=20, verbose_name='Statut licence'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profiles', to='scouting.technicianstructure', verbose_name='Structure'),
        ),
        migrations.CreateModel(
            name='ProducerTechnicianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Affectation active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Affecte le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin affectation')),
                ('end_reason', models.CharField(blank=True, choices=[('admin_removed', 'Retrait admin'), ('technician_stop', 'Arret suivi technicien'), ('technician_disabled', 'Technicien desactive'), ('reassigned', 'Reaffectation')], max_length=30, verbose_name='Motif de fin')),
                ('message', models.TextField(blank=True, help_text='Message affiche au producteur si son acces passe en lecture seule.', verbose_name='Message producteur')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_producer_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Affecte par')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_producer_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Termine par')),
                ('producer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_assignments', to='scouting.userprofile', verbose_name='Producteur')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
            ],
            options={
                'verbose_name': 'Affectation technicien/producteur',
                'verbose_name_plural': 'Affectations technicien/producteur',
                'ordering': ['-is_active', '-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('producer_profile', 'technician'), name='unique_active_technician_assignment_per_producer')],
            },
        ),
        migrations.RunPython(bootstrap_access_control_settings, unbootstrap_access_control_settings),
        migrations.RunPython(backfill_legacy_technician_assignments, unbackfill_legacy_technician_assignments),
    ]
