# Generated by Django 5.2.3 on 2026-04-22 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0031_accesscontrolsettings_technicianstructure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianCoFollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('rejected', 'Refusee'), ('partial', 'Partielle')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Traite le')),
                ('source_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_cofollow_requests', to=settings.AUTH_USER_MODEL, verbose_name='Technicien source')),
                ('target_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_cofollow_requests', to=settings.AUTH_USER_MODEL, verbose_name='Technicien cible')),
            ],
            options={
                'verbose_name': 'Demande co-suivi technicien',
                'verbose_name_plural': 'Demandes co-suivi technicien',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianCoFollowRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepte'), ('rejected', 'Refuse')], default='pending', max_length=20, verbose_name='Decision')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Decide le')),
                ('producer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofollow_request_items', to='scouting.userprofile', verbose_name='Producteur')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scouting.techniciancofollowrequest', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Producteur demande co-suivi',
                'verbose_name_plural': 'Producteurs demande co-suivi',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('request', 'producer_profile'), name='unique_cofollow_request_item_per_producer')],
            },
        ),
    ]
