# Generated by Django 5.2.3 on 2026-05-18 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0032_techniciancofollowrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Message')),
                ('message_type', models.CharField(choices=[('bsv', 'BSV'), ('alert', 'Alerte'), ('advice', 'Conseil'), ('reminder', 'Rappel')], default='bsv', max_length=20, verbose_name='Type')),
                ('priority', models.CharField(choices=[('info', 'Information'), ('watch', 'Vigilance'), ('urgent', 'Urgent')], default='info', max_length=20, verbose_name='Priorite')),
                ('department', models.CharField(blank=True, max_length=10, verbose_name='Departement')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valable jusqu'au")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoye'), ('archived', 'Archive')], default='draft', max_length=20, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoye le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_bulletins', to=settings.AUTH_USER_MODEL, verbose_name='Technicien auteur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bulletins', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='scouting.crop', verbose_name='Culture')),
            ],
            options={
                'verbose_name': 'Bulletin technicien',
                'verbose_name_plural': 'Bulletins techniciens',
                'ordering': ['-sent_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulletinRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Premiere ouverture')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Derniere ouverture')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'ouvertures")),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Pris connaissance le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajoute le')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_bulletins', to=settings.AUTH_USER_MODEL, verbose_name='Pris connaissance par')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='scouting.bulletinmessage', verbose_name='Bulletin')),
                ('producer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_recipients', to='scouting.userprofile', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Destinataire de bulletin',
                'verbose_name_plural': 'Destinataires de bulletin',
                'ordering': ['producer_profile__farm_name', 'producer_profile__user__username'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'Application'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], max_length=20, verbose_name='Canal')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyee'), ('failed', 'Echec'), ('skipped', 'Ignoree')], default='pending', max_length=20, verbose_name='Statut')),
                ('error', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creee le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyee le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='scouting.bulletinrecipient', verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Livraison de notification',
                'verbose_name_plural': 'Livraisons de notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bulletinrecipient',
            constraint=models.UniqueConstraint(fields=('bulletin', 'producer_profile'), name='unique_bulletin_recipient_per_producer'),
        ),
    ]
