# Generated by Django 5.2.3 on 2026-05-18 08:26

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_TYPES = [
    ('bsv', 'BSV', 1),
    ('alert', 'Alerte', 2),
    ('advice', 'Conseil', 3),
    ('reminder', 'Rappel', 4),
]

DEFAULT_PRIORITIES = [
    ('info', 'Information', 1),
    ('watch', 'Vigilance', 2),
    ('urgent', 'Urgent', 3),
]


def seed_bulletin_options(apps, schema_editor):
    bulletin_type_model = apps.get_model('scouting', 'BulletinMessageType')
    priority_model = apps.get_model('scouting', 'BulletinPriority')

    for code, label, display_order in DEFAULT_TYPES:
        bulletin_type_model.objects.update_or_create(
            code=code,
            defaults={
                'label': label,
                'display_order': display_order,
                'is_active': True,
            },
        )

    for code, label, display_order in DEFAULT_PRIORITIES:
        priority_model.objects.update_or_create(
            code=code,
            defaults={
                'label': label,
                'display_order': display_order,
                'is_active': True,
            },
        )


def migrate_existing_bulletin_metadata(apps, schema_editor):
    seed_bulletin_options(apps, schema_editor)

    bulletin_model = apps.get_model('scouting', 'BulletinMessage')
    bulletin_type_model = apps.get_model('scouting', 'BulletinMessageType')
    priority_model = apps.get_model('scouting', 'BulletinPriority')
    crop_model = apps.get_model('scouting', 'Crop')
    department_model = apps.get_model('scouting', 'Department')

    type_by_code = {row.code: row for row in bulletin_type_model.objects.all()}
    priority_by_code = {row.code: row for row in priority_model.objects.all()}
    fallback_type = type_by_code.get('bsv')
    fallback_priority = priority_by_code.get('info')

    for bulletin in bulletin_model.objects.all():
        message_type = type_by_code.get(getattr(bulletin, 'message_type', '') or '')
        if message_type is None:
            message_type = fallback_type
        if message_type is not None:
            bulletin.types.add(message_type)

        priority = priority_by_code.get(getattr(bulletin, 'priority', '') or '')
        if priority is None:
            priority = fallback_priority
        if priority is not None:
            bulletin.priority_option_id = priority.id

        if getattr(bulletin, 'crop_id', None):
            crop = crop_model.objects.filter(pk=bulletin.crop_id).first()
            if crop:
                bulletin.crops.add(crop)

        department_code = (getattr(bulletin, 'department', '') or '').strip()
        if department_code:
            department = department_model.objects.filter(code=department_code).first()
            if department:
                bulletin.departments.add(department)

        if bulletin.priority_option_id:
            bulletin.save(update_fields=['priority_option'])


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0033_bulletinmessage_bulletinrecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinMessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=120, unique=True, verbose_name='Libelle')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de bulletin',
                'verbose_name_plural': 'Types de bulletin',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='BulletinPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=120, unique=True, verbose_name='Libelle')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Priorite de bulletin',
                'verbose_name_plural': 'Priorites de bulletin',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='bulletinmessage',
            name='crops',
            field=models.ManyToManyField(blank=True, related_name='bulletin_messages', to='scouting.crop', verbose_name='Cultures'),
        ),
        migrations.AddField(
            model_name='bulletinmessage',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='bulletin_messages', to='scouting.department', verbose_name='Departements'),
        ),
        migrations.AddField(
            model_name='bulletinmessage',
            name='types',
            field=models.ManyToManyField(related_name='bulletins', to='scouting.bulletinmessagetype', verbose_name='Types'),
        ),
        migrations.AddField(
            model_name='bulletinmessage',
            name='priority_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scouting.bulletinpriority', verbose_name='Priorite'),
        ),
        migrations.RunPython(migrate_existing_bulletin_metadata, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='bulletinmessage',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='bulletinmessage',
            name='department',
        ),
        migrations.RemoveField(
            model_name='bulletinmessage',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='bulletinmessage',
            name='priority',
        ),
        migrations.RenameField(
            model_name='bulletinmessage',
            old_name='priority_option',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='bulletinmessage',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='scouting.bulletinpriority', verbose_name='Priorite'),
        ),
    ]
