# Generated by Django 5.2.3 on 2026-05-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0034_configurable_bulletin_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bulletins/attachments/', verbose_name='Fichier')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Nom original')),
                ('attachment_type', models.CharField(choices=[('photo', 'Photo'), ('file', 'Piece jointe')], max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajoute le')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scouting.bulletinmessage', verbose_name='Bulletin')),
            ],
            options={
                'verbose_name': 'Fichier de bulletin',
                'verbose_name_plural': 'Fichiers de bulletin',
                'ordering': ['attachment_type', 'original_name', 'id'],
            },
        ),
    ]
