# Generated by Django 5.2.3 on 2026-05-18 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0035_bulletin_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_email_enabled', models.BooleanField(default=True, verbose_name='Recevoir les bulletins par email')),
                ('bulletin_email_urgent_only', models.BooleanField(default=False, verbose_name='Limiter aux bulletins urgents')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Preference de notification',
                'verbose_name_plural': 'Preferences de notification',
            },
        ),
    ]
